name: sales-chat-n8n
description: n8n workflow for chatting with sales data

# Use n8n Docker image
command: ["n8n", "start"]

# Environment variables
env:
  - name: N8N_PORT
    value: "5678"
  - name: N8N_PROTOCOL
    value: "http"
  - name: N8N_HOST
    value: "0.0.0.0"
  - name: WEBHOOK_URL
    value: "https://${DATABRICKS_HOST}/serving-endpoints/${DATABRICKS_APP_NAME}"
  - name: N8N_EDITOR_BASE_URL
    value: "/"
  - name: EXECUTIONS_DATA_PRUNE
    value: "true"
  - name: EXECUTIONS_DATA_MAX_AGE
    value: "168"

# Resource requirements
resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

# Port configuration
port: 5678
